# Generated by Django 4.1.7 on 2026-02-17 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Gym Teacher')], max_length=10)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(help_text='Grade level (9-12)')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('fitness_goals', models.TextField(blank=True, help_text='Personal fitness goals')),
                ('preferred_activities', models.CharField(blank=True, help_text='Comma-separated list of preferred activities', max_length=200)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['grade_level', 'student_id'],
            },
        ),
        migrations.CreateModel(
            name='GymTeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('specialization', models.CharField(blank=True, help_text='e.g., Basketball, Swimming, Fitness Training', max_length=100)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('certification', models.CharField(blank=True, help_text='Professional certifications', max_length=200)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
